services:

  db:
    container_name: db
    restart: on-failure
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nexus
      MYSQL_USER: nexususer
      MYSQL_PASSWORD: nexuspassword
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  nexus:
    container_name: nexus
    restart: on-failure
    image: nexus:latest
    depends_on:
      - db
    links:
      - db
    ports:
      - "3020:3010"
    environment:
      NEXUS_MYSQL_CONNECTION_STRING: mysql://root:rootpassword@db:3306/nexus
      NEXUS_SERVER_API_HOST: http://localhost:3020
      NEXUS_SERVER_USERS: "YWRtaW46MTIzNDU2"
