apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
data:
  init.sql: |
    -- Desabilitar verificação de chaves estrangeiras para facilitar o DROP
    SET FOREIGN_KEY_CHECKS = 0;

    DROP DATABASE IF EXISTS `nexus`;

    SET NAMES utf8mb4;
    SET CHARACTER SET utf8mb4;

    CREATE DATABASE `nexus`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

    USE `nexus`;

    -- Drop das tabelas caso já existam
    DROP TABLE IF EXISTS journeys;
    DROP TABLE IF EXISTS services;
    DROP TABLE IF EXISTS products;
    DROP TABLE IF EXISTS journey_categories;
    DROP TABLE IF EXISTS projects;
    DROP TABLE IF EXISTS teams;

    -- Reabilitar verificação de chaves estrangeiras
    SET FOREIGN_KEY_CHECKS = 1;

    -- 1. Tabela: teams
    CREATE TABLE teams (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL UNIQUE,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        active TINYINT(1) DEFAULT 1
    ) CHARACTER SET utf8mb4;;

    -- 2. Tabela: projects
    CREATE TABLE projects (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL UNIQUE,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        active TINYINT(1) DEFAULT 1
    ) CHARACTER SET utf8mb4;;


    -- 3. Tabela: products
    CREATE TABLE products (
        id INT AUTO_INCREMENT PRIMARY KEY,
        id_team INT NOT NULL,
        name VARCHAR(255) NOT NULL UNIQUE,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        active TINYINT(1) DEFAULT 1,
        CONSTRAINT fk_product_team FOREIGN KEY (id_team) REFERENCES teams(id)
    ) CHARACTER SET utf8mb4;;

    -- 4. Tabela: journey_categories
    CREATE TABLE journey_categories (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL UNIQUE,
        description TEXT DEFAULT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        active TINYINT(1) DEFAULT 1
    ) CHARACTER SET utf8mb4;;

    -- 5. Tabela: services
    CREATE TABLE services (
        id INT AUTO_INCREMENT PRIMARY KEY,
        id_product INT NOT NULL,
        name VARCHAR(255) NOT NULL,
        description TEXT DEFAULT NULL,
        dependency_product_ids VARCHAR(600) NULL, -- Ex: 1,2,3
        orr TEXT DEFAULT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        active TINYINT(1) DEFAULT 1,
        CONSTRAINT fk_service_product FOREIGN KEY (id_product) REFERENCES products(id)
    ) CHARACTER SET utf8mb4;;

    -- 6. Tabela: journeys
    CREATE TABLE journeys (
        id INT AUTO_INCREMENT PRIMARY KEY,
        id_journey_category INT NOT NULL,
        id_project INT NOT NULL,
        service_ids VARCHAR(600) NOT NULL, -- Ex: 1,2,3
        name VARCHAR(255) NOT NULL,
        description TEXT DEFAULT NULL,
        critical TINYINT(1) DEFAULT 0,
        integrated_tests TINYINT(1) DEFAULT 0,
        slo TEXT DEFAULT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        active TINYINT(1) DEFAULT 1,
        CONSTRAINT fk_journey_category FOREIGN KEY (id_journey_category) REFERENCES journey_categories(id),
        CONSTRAINT fk_journey_project FOREIGN KEY (id_project) REFERENCES projects(id)
    ) CHARACTER SET utf8mb4;;

    ALTER SCHEMA `nexus`  DEFAULT COLLATE utf8mb4_unicode_ci;

    -- 1. Insert Teams
    INSERT INTO teams (name) VALUES 
    ('Mythbusters'),
    ('Gyodai'),
    ('CloudWalkers'),
    ('Machi Picchu'),
    ('Ringo Starr'),
    ('Elpis'),
    ('MAAT'),
    ('Pressman'),
    ('Defy Hope'),
    ('Ghost'),
    ('Armada'),
    ('Containers PaaS'),
    ('Containers Products'),
    ('Moneyball'),
    ('Zeno');

    -- 2. Insert Projects
    INSERT INTO projects (name) VALUES 
    ('Camada Zero');

    -- 3. Insert Products (Referencing id_team)
    INSERT INTO products (id_team, name) VALUES 
    (1, 'Compass Router HTTP'),
    (1, 'Compass Router Kafka'),
    (2, 'Compass Data'),
    (2, 'CompassDB'),
    (2, 'Compass HC'),
    (1, 'Compass Reconciliator HTTP'),
    (1, 'Compass Reconciliator Kafka'),
    (3, 'Cloud Adapter'),
    (7, 'CEEP'),
    (9, 'Controlplane (Agent)'),
    (9, 'czctl'),
    (4, 'WebConsole'),
    (10, 'Pipelines');

    -- 4. Insert Services (Referencing id_product)
    -- INSERT INTO services 
    -- (id_product, name, description) 
    -- VALUES 
    -- (13,  'Carregar célula', 'Orquestrador para colocar uma célula em carga'),
    -- (11, 'Carregar célula', 'CLI para colocar uma célula em carga'),
    -- (10,  'Carregar célula', 'API para colocar uma célula em carga pelo controlplane'),
    -- (1,  'Carregar célula', 'API para colocar uma célula em carga pelo Compass');

    -- 5. Insert Journey Categories
    INSERT INTO journey_categories
    (name, description) 
    VALUES 
    ('On Boarding', 'Jornadas relacionadas ao processo de on boarding'),
    ('Pós On Boarding', 'Jornadas relacionadas ao processo de pós on boarding'),
    ('Deployments', 'Jornadas relacionadas ao processo de deploy'),
    ('Ações de Crise', 'Jornadas relacionadas a ações específicas, como colocar uma célula em carga');

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: mysql:8.4

          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword

            - name: MYSQL_DATABASE
              value: nexus

            - name: MYSQL_USER
              value: nexususer

            - name: MYSQL_PASSWORD
              value: nexuspassword

          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: initdb
          configMap:
            name: mysql-initdb

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: leandrocurioso/nexus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3010
          env:
            - name: NEXUS_MYSQL_CONNECTION_STRING
              value: "mysql://root:rootpassword@db.default.svc.cluster.local:3306/nexus"

            - name: NEXUS_SERVER_API_HOST
              value: "http://localhost:3020"

            - name: NEXUS_SERVER_USERS
              value: "YWRtaW46MTIzNDU2"

---

apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  type: ClusterIP
  selector:
    app: nexus
  ports:
    - name: http
      port: 3010
      targetPort: 3010
